version: 0.0
os: linux
files:
  - sources: /
    destination: /home/ec2-user/express-app
hooks:
  ApplicationStop:
    - location: scripts/applications_stop.sh
      timeout: 300
      runas: ec2-user
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: ec2-user
  ApplicaitonStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: ec2-user
